### PR TITLE
Travis setup

### LINKED ISSUE #1: Initial set up
- [ ] Travis (& Dockerfile)
- [ ] `notebooks` subfolder
- [ ] training dataset (`data` ?)

### PR DESCRIPTION
**Pull request by sbesson**
Resolves #1 

This PR:
- moves the notebook under a `notebooks` subfolder
- copies the training data under `data`
- adds a top-level Dockerfile to execute the notebook
- sets up Travis to run the Dockerfile and validate the notebook per PR

I kept the `${HOME}/notebooks/UGent/BaF3` structure for the CMSO fileset sample. However, since this is training material, I wonder whether we should flatten it and put it under `${HOME}/notebooks` with a simple readme.txt under `data/` explaining the provenance.

### CODE REVIEW

**Comment by pcmasuzzo** [comment]
Very nice, thanks @sbesson 

One thing to discuss/act upon is the hierarchy of folders under `data`.
Either we change the notebook to read from `data`\etc or we add hierarchical layers of folder under `data`.

**Comment by sbesson** [comment]
Right now this PR leaves the repo in a hybrid place (no hierarchy under `/data` but a hierarchy in the Docker image to match the existing notebook.

My preference goes towards flattening the hierarchy and removing the

```
old_cwd = os.getcwd()
os.chdir(os.path.join("UGent", "BaF3"))
```

steps in the notebooks which make it not idempotent (try to run the second cell twice in a row for instance).

**Comment by pcmasuzzo** [comment]
Yes, I agree with this solution, @sbesson 
Can you please change the notebook (delete 

`old_cwd = os.getcwd()
os.chdir(os.path.join("UGent", "BaF3"))`)

and push? then we can merge.

**Comment by sbesson** [comment]
@pcmasuzzo pushed

**Comment by pcmasuzzo** [comment]
thx @sbesson

**Pull request merged**
